all: test_I8080.cpp I8080.cpp I8080.h
	g++ -o test_I8080 src/test_I8080.cpp src/I8080.cpp

clean:
	rm -f test_I8080


test:
	g++ -o main src/main.cpp -lmingw32 -lSDL2main -lSDL2
	./main


sound:
	g++ -o main src/main.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_mixer
	./main

sound_i8080:
	g++ -o main src/main.cpp src/I8080.cpp src/IO_device.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_mixer
	./main
platform:
	g++ -o main src/main.cpp src/I8080.cpp src/IO_device.cpp src/Platform.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_mixer
	./main